config/routes.rb
Rails.application.routes.draw do
  post 'admin/delete'
  post 'admin/reset'
  get 'admin/index'
  get 'dashboard/index'
  get 'dashboard', to: 'dashboard#index'
  get "/dashboard/all", to: "dashboard#allStudents"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :students
  get "/", to: "login#index", as: 'homepage'
  get "/login/student", to: "login#student"
  post "/login/student", to: "login#post_student"
  get "/register", to: "login#register"
  post "/register", to: "login#post_register"
  get "/login/employer", to: "login#employer"
  post "/login/employer", to: "login#post_employer"
  get "/admin", to: "login#admin"
  post "/admin", to: "login#post_admin"
  get "/logoutredirect", to: "login#logout"
end

app/models/student.rb
class Student < ActiveRecord::Base
    has_one :account, dependent: :destroy, :foreign_key => "account_id"
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def student_params
    params.require(:student).permit(:firstName, :lastName, :graduationMonth, :graduationYear, :bioText, :locationPreference1,
    :locationPreference2, :locationPreference3, :availability, :resumeLink)
  end

  def edit
    @student = Student.find params[:id]

    #Attempt to find session from database that matches sessionhash in session
    user_session = Session.find_by(sessionhash: session[:hash])
    user_account_id = user_session.account_id
    user_account = Account.find(user_account_id)

    student_account = Student.find(params[:id])
    #puts "Student ID: #{student_account.id}"

    #Redirect if different or no hash is found
    if student_account.id != user_account.account_id
        #puts "Account ID: #{user_account.accountId} for user #{user_account.username}"
        redirect_to '/'
    end

    @date = Date.today
    # Get all 12 months
    @months = []
    (1..12).each do |m|
      @months << [Date::MONTHNAMES[m]]
    end
    # Get next 10 years
    @years = []
    (0..9).each do |y|
      @years << [@date.next_year(y).strftime("%Y")]
    end
  end

  def update
    @student = Student.find params[:id]
    @student.update_attributes!(student_params)
    redirect_to student_path(params[:id]);
  end

  def show
    @student = Student.find params[:id]

    # If no session found then redirect to root
    user_session = Session.find_by(sessionhash: session[:hash])
    if user_session == nil then
      redirect_to '/' and return
    end
    user_account_id = user_session.account_id
    user_account = Account.find(user_account_id)
    #If no account found then clear session and redirect
    if user_account == nil then
      redirect_to '/logoutredirect'
    end

    #If student account then view of other student profiles are limited
    if user_account.accountType == 0
      student_account = Student.find(params[:id])
      puts "Student ID: #{student_account.id}"

      #Redirect if logged in student does not match student viewed
      if student_account.id != user_account.account_id
        puts "Account ID: #{user_account.account_id} for user #{user_account.username}"
        redirect_to '/' and return
      end
    end
      
    @atype = user_account.accountType
     
    #Redirect for url pointing to non existing record
    rescue ActiveRecord::RecordNotFound
    redirect_to '/', :flash => { :error => "Record not found." }
  end
end

app/views/students/edit.html.erb
<div class="section" id="welcome-hero">
    <div class="box" id="student-profile">
      <h1 class="title">
        <% if @student.firstName.nil? || @student.firstName.empty? %>
          New profile creation
        <% else %>
          Editing <%= @student.firstName %> <%= @student.lastName %>'s profile
        <% end %>
      </h1>
      <hr/>
      <%= form_tag(student_path(@student), method: "put") do %>
        <div class="field">
          <label class="label">First Name</label>
          <div class="control">
            <%= text_field :student, :firstName, :class => "input", :required => true %>
          </div>
        </div>
        <div class="field">
          <label class="label">Last Name</label>
          <div class="control">
            <%= text_field :student, :lastName, :class => "input", :required => true %>
          </div>
        </div>
        <div class="field">
          <label class="label">Graduation Month</label>
          <div class="control">
            <div class="select">
              <%= select :student, :graduationMonth, @months%>
            </div>
          </div>
        </div>
        <div class="field">
          <label class="label">Graduation Year</label>
          <div class="control">
            <div class="select">
              <%= select :student, :graduationYear, @years%>
            </div>
          </div>
        </div>
        <div class="field">
          <label class="label">About Me</label>
          <div class="control">
            <%= text_area :student, :bioText, :class => "textarea" %>
          </div>
        </div>
        <div class="field">
          <label class="label">Location Preference 1</label>
          <div class="control">
            <%= text_field :student, :locationPreference1, :class => "input" %>
          </div>
        </div>
        <div class="field">
          <label class="label">Location Preference 2</label>
          <div class="control">
            <%= text_field :student, :locationPreference2, :class => "input" %>
          </div>
        </div>
        <div class="field">
          <label class="label">Location Preference 3</label>
          <div class="control">
            <%= text_field :student, :locationPreference3, :class => "input" %>
          </div>
        </div>
        <div class="field">
          <label class="label">Availability</label>
          <div class="control">
            <div class="select">
              <%= select :student, :availability, ['Full & Part time', 'Full time', 'Part time'] %>
            </div>
          </div>
        </div>
        <div class="field">
          <label class="label">Resume Link</label>
          <div class="control">
            <%= text_field :student, :resumeLink, :class => "input" %>
          </div>
        </div>
        <%= submit_tag "Update", class: "button is-success" %>
      <% end %>
    </div>
</div>

app/views/students/show.html.erb
<div class="section" id="welcome-hero">
    <div class="box" id="student-profile">
        <div>
          <% unless @atype == 0 %>
            <a href="/dashboard" class="button is-link" style="float:left;">Back</a>
            <h1 class="title" style="float:right;">Profile for <%= @student.firstName %> <%= @student.lastName%></h1>
          <% else %>
            <h1 class="title">Profile for <%= @student.firstName %> <%= @student.lastName%></h1>
          <% end %>
        </div>
        <hr style="clear:both"/>
        <div class="level">
            <h2>Expected graduation date:</h2>
        </div>
        <div class="level">
            <%= @student.graduationMonth%> <%= @student.graduationYear%>
        </div>
        <div class="level">
            <h2>Student biography:</h2>
        </div>
        <div class="level">
            <%= @student.bioText %>
        </div>
        <div class="level">
            <h2>Location preferences:</h2>
        </div>
        <div class="level">
            <%= @student.locationPreference1 %>
            <% unless @student.locationPreference2 == "" || @student.locationPreference2 == nil %>
              <br><%= @student.locationPreference2 %>
            <% end %>
            <% unless @student.locationPreference3 == "" || @student.locationPreference3 == nil %>
              <br><%= @student.locationPreference3 %>
            <% end %>
        </div>
        <div class="level">
            <h2>Availability:</h2>
        </div>
        <div class="level">
            <%= @student.availability %>
        </div>
        <% unless @student.resumeLink.nil? || @student.resumeLink.empty? %>
          <div class="level">
            <h2>Student resume:</h2>
          </div>
          <div class="level">
            <%= link_to 'Resume Link', @student.resumeLink, :id => 'resumelink'%>
          </div>
        <%end%>
        <% unless @atype != 0 %>
          <hr/>
          <div class="level">
            <div class="level-item">
              <%= link_to 'Edit', edit_student_path(@student), :class => 'button is-success'%>
            </div>
            <div class="level-item">
              <%= link_to 'Log Out', logoutredirect_path, :class => 'button is-warning'%>
            </div>
          </div>
        <% end %>
    </div>
</div>