config/routes.rb
Rails.application.routes.draw do
  post 'admin/delete'
  post 'admin/reset'
  get 'admin/index'
  get 'dashboard/index'
  get 'dashboard', to: 'dashboard#index'
  get "/dashboard/all", to: "dashboard#allStudents"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :students
  get "/", to: "login#index", as: 'homepage'
  get "/login/student", to: "login#student"
  post "/login/student", to: "login#post_student"
  get "/register", to: "login#register"
  post "/register", to: "login#post_register"
  get "/login/employer", to: "login#employer"
  post "/login/employer", to: "login#post_employer"
  get "/admin", to: "login#admin"
  post "/admin", to: "login#post_admin"
  get "/logoutredirect", to: "login#logout"
end

app/views/admin/index.html.erb
<!-- JS Currently not working as intended -->
<% content_for :head do %>
  <%= javascript_include_tag 'admin_page' %>
  <%= javascript_include_tag 'datatables' %>
<% end %>

<header>
   <section class="hero has-background-white">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">
            Admin Dashboard
              <p style="float: right">
            <%= link_to 'Log Out', logoutredirect_path, :class => 'button is-warning'%>
              </p>
          </h1>
          <h2 class="subtitle">
            Listing of current students, employers, and alumni
          </h2> 
        </div>
          
      </div>
    </section>
</header>

<table id="students" class="display" style="width:100%">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Account Type</th>
                <th>Password</th>
                <th>ID</th>
                <th>Account Status</th>
            </tr>
        </thead>
        <tbody>
            <% @students.each do |student| %>
                <tr>
                    <td class="first-name">
                        <%= link_to student.firstName, student_path(student.id)  %> 
                    </td>
                    <td class="last-name">
                        <%= link_to student.lastName, student_path(student.id)  %> 
                    </td>
                    <td class="email">Email Placeholder</td>
                    <td class="account-type">
                      Account Type Placeholder
                    </td>
                    <td class="password-reset">
                        <%= button_to "Reset", admin_reset_path(id: student.id), data: {confirm: "Are you sure you want to reset this password?"}, disabled: false%> 
                    </td>
                    <td class="id">
                        <%= student.id  %> 
                    </td>
                    <td class="delete-account">                           
                        <%= button_to "Delete", admin_delete_path(id: student.id), data: {confirm: "Are you sure you want to delete this account?"}, disabled: false%> 
                    </td>                              
                </tr>
            <% end %>
        </tbody>
        <tfoot>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Account Type</th>
                <th>Password</th>
                <th>ID</th>
                <th>Account Status</th>
            </tr>
        </tfoot>
</table>

<script>
$(document).ready(function() {
    $("#students").DataTable();
} );
</script>